###############################################################
#  Generated by:      Cadence Innovus 21.11-s130_1
#  OS:                Linux x86_64(Host ID pdn.ucsd.edu)
#  Generated on:      Wed Sep  3 17:56:33 2025
#  Design:            ariane
###############################################################
current_design ariane
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk_i}]  -name core_clock -period 1.300000 -waveform {0.000000 0.650000}
