###############################################################
#  Design:            bsg_chip
###############################################################
current_design bsg_chip
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {p_clk_A_i}]  -name bp_clk -period 1.300000 -waveform {0.000000 0.650000}
create_clock [get_ports {p_clk_C_i}]  -name router_clk -period 1.300000 -waveform {0.000000 0.650000}
create_clock [get_ports {p_clk_B_i}]  -name io_master_clk -period 1.300000 -waveform {0.000000 0.650000}
create_clock [get_ports {p_ci2_tkn_i}]  -name sdo_a_tkn_clk -period 2.600000 -waveform {0.000000 1.300000}
create_clock [get_ports {p_co2_tkn_i}]  -name sdo_b_tkn_clk -period 2.600000 -waveform {0.000000 1.300000}
create_clock [get_ports {p_ci_clk_i}]  -name sdi_a_clk -period 2.600000 -waveform {0.000000 1.300000}
create_clock [get_ports {p_co_clk_i}]  -name sdi_b_clk -period 2.600000 -waveform {0.000000 1.300000}
create_clock [get_ports {p_bsg_tag_clk_i}]  -name tag_clk -period 5.200000 -waveform {0.000000 2.600000}
set_input_delay -add_delay 1.456 -clock [get_clocks {tag_clk}] [get_ports {p_bsg_tag_en_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_v_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_v_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_v_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_v_i}]
set_input_delay -add_delay 1.456 -clock [get_clocks {tag_clk}] [get_ports {p_bsg_tag_data_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_7_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_7_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_7_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_7_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_4_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_4_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_4_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_4_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_1_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_1_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_1_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_1_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_8_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_8_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_8_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_8_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_5_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_5_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_5_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_5_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_2_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_2_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_2_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_2_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_6_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_6_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_6_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_6_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_3_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_3_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_3_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_3_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_0_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_0_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_0_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_0_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_7_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_7_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_7_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_7_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_v_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_v_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_v_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_v_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_4_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_4_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_4_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_4_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_1_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_1_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_1_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_1_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_8_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_8_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_8_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_8_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_5_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_5_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_5_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_5_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_2_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] [get_ports {p_co_2_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_2_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_b_clk}] -clock_fall [get_ports {p_co_2_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_6_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_6_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_6_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_6_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_3_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_3_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_3_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_3_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_0_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] [get_ports {p_ci_0_i}]
set_input_delay -add_delay 0.052 -min -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_0_i}]
set_input_delay -add_delay 0.728 -max -clock [get_clocks {sdi_a_clk}] -clock_fall [get_ports {p_ci_0_i}]
set_clock_uncertainty 0.15 -hold [get_clocks {tag_clk}]
set_clock_uncertainty 0.15 [get_clocks {sdo_b_tkn_clk}]
set_clock_uncertainty 0.15 [get_clocks {sdo_a_tkn_clk}]
set_clock_uncertainty 0.15 [get_clocks {bp_clk}]
set_clock_uncertainty 0.15 [get_clocks {router_clk}]
set_clock_uncertainty 0.15 [get_clocks {sdi_b_clk}]
set_clock_uncertainty 0.15 [get_clocks {io_master_clk}]
set_clock_uncertainty 0.15 [get_clocks {sdi_a_clk}]
set_multicycle_path 1 -setup  -to [get_ports {p_ci2_8_o p_ci2_7_o p_ci2_6_o p_ci2_5_o p_ci2_4_o p_ci2_3_o p_ci2_2_o p_ci2_1_o p_ci2_0_o p_ci2_v_o p_ci2_clk_o p_co2_8_o p_co2_7_o p_co2_6_o p_co2_5_o p_co2_4_o p_co2_3_o p_co2_2_o p_co2_1_o p_co2_0_o p_co2_v_o p_co2_clk_o}] 
set_false_path  -from [get_clocks {router_clk tag_clk}] -to [get_clocks {bp_clk}]
